### ISSUE TITLE
Allow for flash messages to be sent with an `id`

### ISSUE THREAD

**Issue by Scalahansolo** [camilosw/flash-messages#16]
It would be a nice feature to be able to send a FlashMessages with an `id` so that it would be possible to have multiple flash messages on the same page that would act independent of each other.

**Comment by mscherer82** [comment]
I forked and added namespaces. Please have a look at https://github.com/mscherer82/flash-messages. I put the namespace in options because I didn't want to change the API. I will add tests later and create a pull request.
