### ISSUE TITLE
Uncaught ReferenceError: FlashMessages is not defined 

### ISSUE THREAD

**Issue by sherry-liveitchina** [camilosw/flash-messages#4]
Hi, 

I'm trying to add the FlashMessages.sendSuccess("HELLO"); in the template events but I'm getting the error "Uncaught ReferenceError: FlashMessages is not defined". But when I put it in template rendered it's working. Any ideas why? Thank you

**Comment by neilyoung** [comment]
FlashMessages is not defined - same here :/
Called in explicit client code

**Comment by neilyoung** [comment]
The reason:

meteor add mrt:flash-messages  ---- works
meteor add kmligue:flash-messages   ---- does not work
